-- AUTO INCREMENT PK ON BRAND

CREATE SEQUENCE BRAND_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER BRAND_TRIG
BEFORE INSERT ON BRAND
FOR EACH ROW
BEGIN
    IF( :new.ID IS NULL)
    THEN
        :new.ID := BRAND_SEQ.NEXTVAL;
    END IF;
END;


-- AUTO INCREMENT PK ON CATHEGORY

CREATE SEQUENCE CATHEGORY_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER CATHEGORY_TRIG
BEFORE INSERT ON CATHEGORY
FOR EACH ROW
BEGIN
    IF( :new.ID IS NULL)
    THEN
        :new.ID := CATHEGORY_SEQ.NEXTVAL;
    END IF;
END;


-- AUTO INCREMENT PK ON IMAGE

CREATE SEQUENCE IMAGE_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER IMAGE_TRIG
BEFORE INSERT ON IMAGE
FOR EACH ROW
BEGIN
    IF( :new.ID IS NULL)
    THEN
        :new.ID := IMAGE_SEQ.NEXTVAL;
    END IF;
END;


-- AUTO INCREMENT PK ON LOCALIZATION

CREATE SEQUENCE LOCALIZATION_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER LOCALIZATION_TRIG
BEFORE INSERT ON LOCALIZATION
FOR EACH ROW
BEGIN
    IF( :new.ID IS NULL)
    THEN
        :new.ID := LOCALIZATION_SEQ.NEXTVAL;
    END IF;
END;


-- AUTO INCREMENT PK ON PARAMS

CREATE SEQUENCE PARAMS_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER PARAMS_TRIG
BEFORE INSERT ON PARAMS
FOR EACH ROW
BEGIN
    IF( :new.ID IS NULL)
    THEN
        :new.ID := PARAMS_SEQ.NEXTVAL;
    END IF;
END;


-- AUTO INCREMENT PK ON PARAMS_TYPES

CREATE SEQUENCE PARAMS_TYPES_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER PARAMS_TYPES_TRIG
BEFORE INSERT ON PARAMS_TYPES
FOR EACH ROW
BEGIN
    IF( :new.ID IS NULL)
    THEN
        :new.ID := PARAMS_TYPES_SEQ.NEXTVAL;
    END IF;
END;


-- AUTO INCREMENT PK ON PRODUCT

CREATE SEQUENCE PRODUCT_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER PRODUCT_TRIG
BEFORE INSERT ON PRODUCT
FOR EACH ROW
BEGIN
    IF( :new.ID IS NULL)
    THEN
        :new.ID := PRODUCT_SEQ.NEXTVAL;
    END IF;
END;

/
