INSERT INTO BRAND (NAME) VALUES('Samsung');
INSERT INTO CATHEGORY (NAME) VALUES('Smartphone');
INSERT INTO PRODUCT (BRANDID,CATHEGORYID,NAME,COLOR,PRICE,GRADE) VALUES(1,1,'Galaxy S8', 'black', 3298.00, 5);
INSERT INTO LOCALIZATION (PRODUCTID,CITY,STREET,AVAIL,QUANTITY) VALUES(1,'Lodz','Kolumny 6/36', 1, 10);

INSERT INTO PARAMS_TYPES (NAME) VALUES('Screen');
INSERT INTO PARAMS_TYPES (NAME) VALUES('Camera');
INSERT INTO PARAMS_TYPES (NAME) VALUES('Memory');
INSERT INTO PARAMS_TYPES (NAME) VALUES('Battery');

INSERT INTO PARAMS (PRODUCTID,PARAMSTYPESID, VALUE) VALUES(1,1,'5.8, HD+, Proporcje: 18.5:9');
INSERT INTO PARAMS (PRODUCTID,PARAMSTYPESID, VALUE) VALUES(1,2,'Rear: 12MP, FRONT: 8MP');
INSERT INTO PARAMS (PRODUCTID,PARAMSTYPESID, VALUE) VALUES(1,3,'Internal: 64GB');
INSERT INTO PARAMS (PRODUCTID,PARAMSTYPESID, VALUE) VALUES(1,3,'3000 mAh');

INSERT INTO PARAMS_CATHEGORY (CATHEGORYID, PARAMSTYPESID) VALUES(1,1);
INSERT INTO PARAMS_CATHEGORY (CATHEGORYID, PARAMSTYPESID) VALUES(1,2);
INSERT INTO PARAMS_CATHEGORY (CATHEGORYID, PARAMSTYPESID) VALUES(1,3);
INSERT INTO PARAMS_CATHEGORY (CATHEGORYID, PARAMSTYPESID) VALUES(1,4);

/